[".local/bin/mise"]
url = 'https://github.com/jdx/mise/releases/latest/download/mise-{{ (gitHubLatestRelease "jdx/mise").TagName }}-{{ .chezmoi.os }}-{{ if eq .chezmoi.arch "amd64" }}x64{{ else }}{{ .chezmoi.arch }}{{ end }}.tar.gz'
refreshPeriod = "168h"
type = "archive-file"
path = "mise/bin/mise"
