[".local/bin/rtx"]
url = 'https://github.com/jdx/rtx/releases/latest/download/rtx-{{ (gitHubLatestRelease "jdx/rtx").TagName }}-{{ .chezmoi.os }}-{{ if eq .chezmoi.arch "amd64" }}x64{{ else }}{{ .chezmoi.arch }}{{ end }}.tar.gz'
refreshPeriod = "168h"
type = "archive-file"
path = "rtx/bin/rtx"
