[".local/bin/uad"]
url = 'https://github.com/0x192/universal-android-debloater/releases/download/{{ (gitHubLatestTag "0x192/universal-android-debloater").Name }}/uad_gui-linux.tar.gz'
refreshPeriod = "168h"
type = "archive-file"
path = "uad_gui-linux"
