[".config/zshrc.d/plugins/zsh-syntax-highlighting"]
url = "https://github.com/zsh-users/zsh-syntax-highlighting"
refreshPeriod = "168h"
type = "git-repo"

[".config/zshrc.d/plugins/zsh-autosuggestions"]
url = "https://github.com/zsh-users/zsh-autosuggestions"
refreshPeriod = "168h"
type = "git-repo"

[".config/zshrc.d/plugins/catppuccin.sh"]
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"
refreshPeriod = "168h"
type = "file"

[".config/zshrc.d/plugins/zsh-fsh"]
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
refreshPeriod = "168h"
type = "git-repo"


[".config/zshrc.d/plugins/catppuccin-mocha.ini"]
url = "https://raw.githubusercontent.com/catppuccin/zsh-fsh/main/themes/catppuccin-mocha.ini"
refreshPeriod = "168h"
type = "file"
