[".config/zshrc.d/plugins/zsh-syntax-highlighting"]
url = "https://github.com/zsh-users/zsh-syntax-highlighting"
refreshPeriod = "168h"
type = "git-repo"

[".config/zshrc.d/plugins/catppuccin.sh"]
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"
refreshPeriod = "168h"
type = "file"
