[tools]
fzf = "latest"
tmux = "latest"
lazygit = "latest"
starship = "latest"
pre-commit = "latest"
neovim = "stable"
python = "latest"
poetry = "latest"
node = "lts"
pnpm = "latest"

[settings]
experimental = true
