[env]
NODE_REPL_HISTORY = ""
TS_NODE_HISTORY = ""

[tools]
fzf = "latest"
tmux = "latest"
lazygit = "latest"
starship = "latest"
pre-commit = "latest"
neovim = "stable"
python = "latest"
poetry = "latest"
node = "lts"
pnpm = "latest"
zoxide = "latest"
zig = "latest"

[settings]
experimental = true
